config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.views import contacts, ProductCreateView, ProductDetailView, ProductUpdateView, \
    ProductDeleteView, BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView, \
    product_version_list, VersionCreateView


app_name = 'main'


urlpatterns = [
    path('', product_version_list, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/edit/<int:pk>/', ProductUpdateView.as_view(), name='product_edit'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    path('product/<int:pk>/version/', VersionCreateView.as_view(), name='version_create'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import UserCreateView, VerifyCodeView, success_view, reset_password
from users.models import User

app_name = 'users'

urlpatterns = [path('registration/', UserCreateView.as_view(), name='user_create'),
               path('verify/', VerifyCodeView.as_view(), name='verify_code'),
               path('registration/success/', success_view, name='success_regist'),
               path('login/', LoginView.as_view(template_name='user/user_login.html'), name='login'),
               path('logout/', LogoutView.as_view(template_name='user/user_logout.html'), name='logout'),
               path('reset_password/', reset_password, name='reset_password')]

main/models.py
from django.db import models
from django.utils import timezone

from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='название категории')
    description = models.TextField(verbose_name='описание категории')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='название продукта', unique=True)
    description = models.TextField(verbose_name='описание продукта')
    preview = models.ImageField(upload_to='product',verbose_name='превью', null=True, blank=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT, null=True, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена')
    date = models.DateField(default=timezone.now, verbose_name='дата создания', null=True)
    modified_at = models.DateField(verbose_name='дата последнего изменения', null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',) # порядок с какого поля начнется


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='слаг', null=True, blank=True)
    content = models.TextField(verbose_name='содержание')
    preview = models.ImageField(upload_to='blog', verbose_name='превью блога', null=True, blank=True)
    date = models.DateField(default=timezone.now, verbose_name='дата создания', null=True)
    sign_of_blog = models.BooleanField(default=True, verbose_name='признак публикации')
    number_of_views = models.IntegerField(default=0, verbose_name='количество просмотров')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ('title',)


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='продукт')
    number_of_version = models.IntegerField(default=0, verbose_name='номер версии')
    name_of_version = models.CharField(max_length=100, verbose_name='название версии')
    is_active = models.BooleanField(default=True, verbose_name='признак версии')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'{self.name_of_version} ({self.number_of_version})'


    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

main/forms.py
from django import forms

from main.models import Product, Version


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        bad_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in bad_words:
            if word in cleaned_data:
                raise forms.ValidationError('Название продукта не должно содержать такие слова')

        return cleaned_data


    def clean_description(self):
        cleanned_data = self.cleaned_data['description']
        bad_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in bad_words:
            if word in cleanned_data:
                raise forms.ValidationError('Описание продукта не должно содержать такие слова')

        return cleanned_data


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from main.forms import ProductForm, VersionForm
from main.models import Product, Blog, Version


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name}({phone}): {message}')
    return render(request, 'main/contacts.html')


@method_decorator(login_required, name='dispatch')
class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('main:home')

    def form_valid(self, form):
        new_product = form.save(commit=False)
        new_product.owner = self.request.user
        new_product.save()
        return super().form_valid(form)


class ProductListView(ListView):
    model = Product
    template_name = 'main/home.html'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'main/product_id.html'


@method_decorator(login_required, name='dispatch')
class ProductUpdateView(UpdateView):
    model = Product
    fields = ('name', 'description', 'preview', 'price', 'date', 'modified_at',)
    success_url = reverse_lazy('main:home')
    template_name = 'main/product_edit.html'


@method_decorator(login_required, name='dispatch')
class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('main:home')


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(sign_of_blog=True)
        return queryset


@method_decorator(login_required, name='dispatch')
class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('main:blog_list')

    def form_valid(self, form):
        new_blog = form.save(commit=False)
        new_blog.owner = self.request.user
        new_blog.slug = slugify(new_blog.title)
        new_blog.save()
        return super().form_valid(form)


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'main/blog_id.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views += 1
        self.object.save()
        return self.object


@method_decorator(login_required, name='dispatch')
class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'slug', 'content', 'preview', 'date', 'sign_of_blog', 'number_of_views',)
    # success_url = reverse_lazy('blog_list')
    template_name = 'main/blog_edit.html'

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main:blog_detail', args=[self.kwargs.get('pk')])


@method_decorator(login_required, name='dispatch')
class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('main:blog_list')


def product_version_list(request):
    products = Product.objects.all()
    active_versions = Version.objects.filter(is_active=True)

    return render(request, 'main/home.html', {'products': products, 'active_versions': active_versions})


@method_decorator(login_required, name='dispatch')
class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('main:product_detail')

    def form_valid(self, form):
        new_version = form.save(commit=False)
        new_version.owner = self.request.user
        new_version.save()
        return super().form_valid(form)

main/templates/main/base.html
{% load static %}

{% block mainmenu %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Магазин</title>
    <link href={% static 'css/bootstrap.min.css' %} rel="stylesheet">
</head>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <a href="/" class="btn btn-outline-primary">Магазин</a>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="/blog/">Блог</a>
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-success" href="{% url 'users:logout'%}">Выйти</a>
        {% else %}
        <a class="p-2 btn btn-success" href="{% url 'users:login'%}">Войти</a>
        <a class="p-2 btn btn-success" href="/users/registration">Регистрация</a>
        {% endif %}

    </nav>
    </div>
    {% endblock mainmenu%}
{% block content %}
{% endblock %}

main/templates/main/blog_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}

<title>Удаление статьи</title>
    <div class="col">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить продукт "{{ object.title }}"?</p>
                            <button type="submit" name="confirm" value="Confirm" class="btn btn-warning">Подтвердить</button>
                            <a href="{% url 'main:blog_list' %}" class="btn btn-success">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/blog_edit.html
{% extends 'main/base.html' %}

{% block content %}


<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Изменить</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

main/templates/main/blog_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Создать></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

main/templates/main/blog_id.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}
{% load my_tags %}

<link href={% static 'css/style.css' %} rel="stylesheet">
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div class="article-container">
        Просмотры: {{ object.number_of_views }}
        <img class="card-img-top" src="{% mediapath blog.preview %}" alt="Card image cap">
        <h1>{{ blog.title }}</h1>
        <p>Дата написания: {{ blog.date }}</p>

        <div>
            <p>Содержание статьи:</p>
            <p>{{ blog.content }}</p>
        </div>
    </div>
</body>
</html>

{% endblock %}

main/templates/main/blog_list.html
{% extends 'main/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог</h1>

<div class="album py-5 bg-light">
  <a class="btn btn-outline-primary" href="{% url 'main:blog_create' %}">Добавить запись</a>
  <div class="container">
    <div class="row">
      {% for object in object_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top" src="{% mediapath object.preview %}" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">{{ object.title }}</p>
            <p class="card-text">{{ object.content|truncatechars:100 }}</p>
            <p class="card-text">{{ object.date }}</p>
            <p class="card-text">{{ version.name_of_version }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'main:blog_detail' object.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                <a href="{% url 'main:blog_edit' object.pk %}" class="btn btn-sm btn-outline-secondary">Edit</a>
                <a href="{% url 'main:blog_delete' object.pk %}" class="btn btn-sm btn-outline-secondary">Delete</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</div>
</html>
{% endblock %}

main/templates/main/contacts.html
{% extends 'main/base.html' %}
{% load static %}



{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Москва</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                    </form>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Магазин</h1>

  <div class="album py-5 bg-light">
    <a class="btn btn-outline-primary" href="{% url 'main:product_create' %}">Добавить продукт</a>
    <div class="container">
      <div class="row">
        {% for object in products %}
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{% mediapath object.preview %}" alt="Card image cap">
            <div class="card-body">
              <p class="card-text">{{ object.name }}</p>
              <p class="card-text">Описание: {{ object.description|truncatechars:100 }}</p>
              <p class="card-text">{{ object.price }} руб.</p>
              <p class="card-text">{{ object.category }}</p>
              {% for version in active_versions %}
              {% if version.product == object %}
              <p class="card-text">Активная версия: {{ version.name_of_version }} ({{ version.number_of_version }})</p>
              {% endif %}
              {% endfor %}
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'main:product_detail' object.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                  <a href="{% url 'main:product_edit' object.pk %}" class="btn btn-sm btn-outline-secondary">Edit</a>
                  <a href="{% url 'main:product_delete' object.pk %}" class="btn btn-sm btn-outline-secondary">Delete</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>



<script src="/static/js/bootstrap.bundle.min.js"></script>
</div>
</html>
{% endblock %}

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}

<title>Удаление статьи</title>
    <div class="col">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить продукт "{{ product.name }}"?</p>
                            <button type="submit" name="confirm" value="Confirm" class="btn btn-warning">Подтвердить</button>
                            <a href="{% url 'main:home' %}" class="btn btn-success">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/product_edit.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Изменить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

main/templates/main/product_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Создать></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

main/templates/main/product_id.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}
{% load my_tags %}

<link href={% static 'css/style.css' %} rel="stylesheet">
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div class="article-container">
        <a class="btn btn-warning" href="{% url 'main:version_create' product.pk %}">Создать версию</a>
        <img class="card-img-top" src="{% mediapath product.preview %}" alt="Card image cap">
        <h1>{{ product.name }}</h1>
        <p>{{ product.price }} RUB.</p>
        <div>
            <p>Описание: {{ product.description }}</p>
        </div>
    </div>
</body>
</html>

{% endblock %}

main/templates/main/version_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Создать></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}